// Generated by gencpp from file art_msgs/Behavior.msg
// DO NOT EDIT!


#ifndef ART_MSGS_MESSAGE_BEHAVIOR_H
#define ART_MSGS_MESSAGE_BEHAVIOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace art_msgs
{
template <class ContainerAllocator>
struct Behavior_
{
  typedef Behavior_<ContainerAllocator> Type;

  Behavior_()
    : value(0)  {
    }
  Behavior_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef int16_t _value_type;
  _value_type value;


    enum { Abort = 0 };
     enum { Quit = 1 };
     enum { Pause = 2 };
     enum { Run = 3 };
     enum { Suspend = 4 };
     enum { Initialize = 5 };
     enum { Go = 6 };
     enum { NONE = 7 };
     enum { N_behaviors = 8 };
 

  typedef boost::shared_ptr< ::art_msgs::Behavior_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::art_msgs::Behavior_<ContainerAllocator> const> ConstPtr;

}; // struct Behavior_

typedef ::art_msgs::Behavior_<std::allocator<void> > Behavior;

typedef boost::shared_ptr< ::art_msgs::Behavior > BehaviorPtr;
typedef boost::shared_ptr< ::art_msgs::Behavior const> BehaviorConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::art_msgs::Behavior_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::art_msgs::Behavior_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace art_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'art_msgs': ['/home/amogh/rosws2/src/art_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::art_msgs::Behavior_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::art_msgs::Behavior_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::art_msgs::Behavior_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::art_msgs::Behavior_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::art_msgs::Behavior_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::art_msgs::Behavior_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::art_msgs::Behavior_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88d96e38b2c952605ef152e7b2cc38ab";
  }

  static const char* value(const ::art_msgs::Behavior_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88d96e38b2c95260ULL;
  static const uint64_t static_value2 = 0x5ef152e7b2cc38abULL;
};

template<class ContainerAllocator>
struct DataType< ::art_msgs::Behavior_<ContainerAllocator> >
{
  static const char* value()
  {
    return "art_msgs/Behavior";
  }

  static const char* value(const ::art_msgs::Behavior_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::art_msgs::Behavior_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ART Navigator behaviors (lower numbers have higher priority)\n\
# $Id$\n\
\n\
# enumerated behavior values\n\
int16 Abort       = 0\n\
int16 Quit        = 1\n\
int16 Pause       = 2\n\
int16 Run         = 3\n\
int16 Suspend     = 4\n\
int16 Initialize  = 5\n\
int16 Go          = 6\n\
int16 NONE        = 7\n\
int16 N_behaviors = 8\n\
\n\
int16 value\n\
";
  }

  static const char* value(const ::art_msgs::Behavior_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::art_msgs::Behavior_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Behavior_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::art_msgs::Behavior_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::art_msgs::Behavior_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<int16_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ART_MSGS_MESSAGE_BEHAVIOR_H
