// Generated by gencpp from file art_msgs/CarControl.msg
// DO NOT EDIT!


#ifndef ART_MSGS_MESSAGE_CARCONTROL_H
#define ART_MSGS_MESSAGE_CARCONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace art_msgs
{
template <class ContainerAllocator>
struct CarControl_
{
  typedef CarControl_<ContainerAllocator> Type;

  CarControl_()
    : velocity(0.0)
    , angle(0.0)  {
    }
  CarControl_(const ContainerAllocator& _alloc)
    : velocity(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef float _velocity_type;
  _velocity_type velocity;

   typedef float _angle_type;
  _angle_type angle;




  typedef boost::shared_ptr< ::art_msgs::CarControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::art_msgs::CarControl_<ContainerAllocator> const> ConstPtr;

}; // struct CarControl_

typedef ::art_msgs::CarControl_<std::allocator<void> > CarControl;

typedef boost::shared_ptr< ::art_msgs::CarControl > CarControlPtr;
typedef boost::shared_ptr< ::art_msgs::CarControl const> CarControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::art_msgs::CarControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::art_msgs::CarControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace art_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'art_msgs': ['/home/amogh/rosws2/src/art_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::art_msgs::CarControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::art_msgs::CarControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::art_msgs::CarControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::art_msgs::CarControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::art_msgs::CarControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::art_msgs::CarControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::art_msgs::CarControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23ee9ebc4f65684302501539608c3833";
  }

  static const char* value(const ::art_msgs::CarControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23ee9ebc4f656843ULL;
  static const uint64_t static_value2 = 0x02501539608c3833ULL;
};

template<class ContainerAllocator>
struct DataType< ::art_msgs::CarControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "art_msgs/CarControl";
  }

  static const char* value(const ::art_msgs::CarControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::art_msgs::CarControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# car control command\n\
# $Id$\n\
\n\
float32 velocity                # forward velocity (m/s), negative is reverse\n\
float32 angle                   # steering angle (degrees)\n\
";
  }

  static const char* value(const ::art_msgs::CarControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::art_msgs::CarControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::art_msgs::CarControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::art_msgs::CarControl_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ART_MSGS_MESSAGE_CARCONTROL_H
