// Generated by gencpp from file art_msgs/CarCommand.msg
// DO NOT EDIT!


#ifndef ART_MSGS_MESSAGE_CARCOMMAND_H
#define ART_MSGS_MESSAGE_CARCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <art_msgs/CarControl.h>

namespace art_msgs
{
template <class ContainerAllocator>
struct CarCommand_
{
  typedef CarCommand_<ContainerAllocator> Type;

  CarCommand_()
    : header()
    , control()  {
    }
  CarCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , control(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::art_msgs::CarControl_<ContainerAllocator>  _control_type;
  _control_type control;




  typedef boost::shared_ptr< ::art_msgs::CarCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::art_msgs::CarCommand_<ContainerAllocator> const> ConstPtr;

}; // struct CarCommand_

typedef ::art_msgs::CarCommand_<std::allocator<void> > CarCommand;

typedef boost::shared_ptr< ::art_msgs::CarCommand > CarCommandPtr;
typedef boost::shared_ptr< ::art_msgs::CarCommand const> CarCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::art_msgs::CarCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::art_msgs::CarCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace art_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'art_msgs': ['/home/amogh/rosws2/src/art_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::art_msgs::CarCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::art_msgs::CarCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::art_msgs::CarCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::art_msgs::CarCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::art_msgs::CarCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::art_msgs::CarCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::art_msgs::CarCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a9c426b2a11ce63f7116e941449a149d";
  }

  static const char* value(const ::art_msgs::CarCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa9c426b2a11ce63fULL;
  static const uint64_t static_value2 = 0x7116e941449a149dULL;
};

template<class ContainerAllocator>
struct DataType< ::art_msgs::CarCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "art_msgs/CarCommand";
  }

  static const char* value(const ::art_msgs::CarCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::art_msgs::CarCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# car control command with timestamp\n\
# $Id$\n\
\n\
Header     header\n\
CarControl control\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: art_msgs/CarControl\n\
# car control command\n\
# $Id$\n\
\n\
float32 velocity                # forward velocity (m/s), negative is reverse\n\
float32 angle                   # steering angle (degrees)\n\
";
  }

  static const char* value(const ::art_msgs::CarCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::art_msgs::CarCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.control);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::art_msgs::CarCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::art_msgs::CarCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "control: ";
    s << std::endl;
    Printer< ::art_msgs::CarControl_<ContainerAllocator> >::stream(s, indent + "  ", v.control);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ART_MSGS_MESSAGE_CARCOMMAND_H
