// Generated by gencpp from file art_msgs/IOadrCommand.msg
// DO NOT EDIT!


#ifndef ART_MSGS_MESSAGE_IOADRCOMMAND_H
#define ART_MSGS_MESSAGE_IOADRCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace art_msgs
{
template <class ContainerAllocator>
struct IOadrCommand_
{
  typedef IOadrCommand_<ContainerAllocator> Type;

  IOadrCommand_()
    : header()
    , relays_on(0)
    , relays_off(0)  {
    }
  IOadrCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , relays_on(0)
    , relays_off(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _relays_on_type;
  _relays_on_type relays_on;

   typedef uint8_t _relays_off_type;
  _relays_off_type relays_off;




  typedef boost::shared_ptr< ::art_msgs::IOadrCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::art_msgs::IOadrCommand_<ContainerAllocator> const> ConstPtr;

}; // struct IOadrCommand_

typedef ::art_msgs::IOadrCommand_<std::allocator<void> > IOadrCommand;

typedef boost::shared_ptr< ::art_msgs::IOadrCommand > IOadrCommandPtr;
typedef boost::shared_ptr< ::art_msgs::IOadrCommand const> IOadrCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::art_msgs::IOadrCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::art_msgs::IOadrCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace art_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'art_msgs': ['/home/amogh/rosws2/src/art_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::art_msgs::IOadrCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::art_msgs::IOadrCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::art_msgs::IOadrCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::art_msgs::IOadrCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::art_msgs::IOadrCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::art_msgs::IOadrCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::art_msgs::IOadrCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ba0a21767ee8a4bb7c80945f20b670c";
  }

  static const char* value(const ::art_msgs::IOadrCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ba0a21767ee8a4bULL;
  static const uint64_t static_value2 = 0xb7c80945f20b670cULL;
};

template<class ContainerAllocator>
struct DataType< ::art_msgs::IOadrCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "art_msgs/IOadrCommand";
  }

  static const char* value(const ::art_msgs::IOadrCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::art_msgs::IOadrCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# NCD IOADR8x controller command message for ART vehicle\n\
#\n\
# Sets or clears relays.  See: IOadrState for bit definitions.\n\
\n\
# $Id$\n\
\n\
Header  header          # standard ROS message header\n\
\n\
uint8 relays_on         # relays to set\n\
uint8 relays_off        # relays to clear\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::art_msgs::IOadrCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::art_msgs::IOadrCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.relays_on);
      stream.next(m.relays_off);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IOadrCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::art_msgs::IOadrCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::art_msgs::IOadrCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "relays_on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relays_on);
    s << indent << "relays_off: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relays_off);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ART_MSGS_MESSAGE_IOADRCOMMAND_H
