// Generated by gencpp from file art_msgs/LearningCommand.msg
// DO NOT EDIT!


#ifndef ART_MSGS_MESSAGE_LEARNINGCOMMAND_H
#define ART_MSGS_MESSAGE_LEARNINGCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace art_msgs
{
template <class ContainerAllocator>
struct LearningCommand_
{
  typedef LearningCommand_<ContainerAllocator> Type;

  LearningCommand_()
    : header()
    , pilotActive(0)  {
    }
  LearningCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pilotActive(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _pilotActive_type;
  _pilotActive_type pilotActive;




  typedef boost::shared_ptr< ::art_msgs::LearningCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::art_msgs::LearningCommand_<ContainerAllocator> const> ConstPtr;

}; // struct LearningCommand_

typedef ::art_msgs::LearningCommand_<std::allocator<void> > LearningCommand;

typedef boost::shared_ptr< ::art_msgs::LearningCommand > LearningCommandPtr;
typedef boost::shared_ptr< ::art_msgs::LearningCommand const> LearningCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::art_msgs::LearningCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::art_msgs::LearningCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace art_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'art_msgs': ['/home/amogh/rosws2/src/art_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::art_msgs::LearningCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::art_msgs::LearningCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::art_msgs::LearningCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::art_msgs::LearningCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::art_msgs::LearningCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::art_msgs::LearningCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::art_msgs::LearningCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ddd1e597cd0c1d6b0d1497108b462a51";
  }

  static const char* value(const ::art_msgs::LearningCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xddd1e597cd0c1d6bULL;
  static const uint64_t static_value2 = 0x0d1497108b462a51ULL;
};

template<class ContainerAllocator>
struct DataType< ::art_msgs::LearningCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "art_msgs/LearningCommand";
  }

  static const char* value(const ::art_msgs::LearningCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::art_msgs::LearningCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Lets us turn on or off different modules using a message\n\
# For example, I can disable pilot for some parts of learning\n\
\n\
# $Id$\n\
\n\
Header     header\n\
int8       pilotActive\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::art_msgs::LearningCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::art_msgs::LearningCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pilotActive);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LearningCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::art_msgs::LearningCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::art_msgs::LearningCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pilotActive: ";
    Printer<int8_t>::stream(s, indent + "  ", v.pilotActive);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ART_MSGS_MESSAGE_LEARNINGCOMMAND_H
