// Generated by gencpp from file art_msgs/MapID.msg
// DO NOT EDIT!


#ifndef ART_MSGS_MESSAGE_MAPID_H
#define ART_MSGS_MESSAGE_MAPID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace art_msgs
{
template <class ContainerAllocator>
struct MapID_
{
  typedef MapID_<ContainerAllocator> Type;

  MapID_()
    : seg(0)
    , lane(0)
    , pt(0)  {
    }
  MapID_(const ContainerAllocator& _alloc)
    : seg(0)
    , lane(0)
    , pt(0)  {
  (void)_alloc;
    }



   typedef uint16_t _seg_type;
  _seg_type seg;

   typedef uint16_t _lane_type;
  _lane_type lane;

   typedef uint16_t _pt_type;
  _pt_type pt;


    enum { NULL_ID = 65535u };
 

  typedef boost::shared_ptr< ::art_msgs::MapID_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::art_msgs::MapID_<ContainerAllocator> const> ConstPtr;

}; // struct MapID_

typedef ::art_msgs::MapID_<std::allocator<void> > MapID;

typedef boost::shared_ptr< ::art_msgs::MapID > MapIDPtr;
typedef boost::shared_ptr< ::art_msgs::MapID const> MapIDConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::art_msgs::MapID_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::art_msgs::MapID_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace art_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'art_msgs': ['/home/amogh/rosws2/src/art_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::art_msgs::MapID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::art_msgs::MapID_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::art_msgs::MapID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::art_msgs::MapID_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::art_msgs::MapID_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::art_msgs::MapID_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::art_msgs::MapID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19289d0a831d333d542743932b12dadc";
  }

  static const char* value(const ::art_msgs::MapID_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19289d0a831d333dULL;
  static const uint64_t static_value2 = 0x542743932b12dadcULL;
};

template<class ContainerAllocator>
struct DataType< ::art_msgs::MapID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "art_msgs/MapID";
  }

  static const char* value(const ::art_msgs::MapID_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::art_msgs::MapID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Road map identifier for segments, lanes and way-points.\n\
# $Id$\n\
\n\
uint16 NULL_ID = 65535\n\
\n\
uint16 seg      # segment ID\n\
uint16 lane     # lane ID\n\
uint16 pt       # way-point ID\n\
";
  }

  static const char* value(const ::art_msgs::MapID_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::art_msgs::MapID_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.seg);
      stream.next(m.lane);
      stream.next(m.pt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapID_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::art_msgs::MapID_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::art_msgs::MapID_<ContainerAllocator>& v)
  {
    s << indent << "seg: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.seg);
    s << indent << "lane: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.lane);
    s << indent << "pt: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.pt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ART_MSGS_MESSAGE_MAPID_H
