// Generated by gencpp from file art_msgs/RoadState.msg
// DO NOT EDIT!


#ifndef ART_MSGS_MESSAGE_ROADSTATE_H
#define ART_MSGS_MESSAGE_ROADSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace art_msgs
{
template <class ContainerAllocator>
struct RoadState_
{
  typedef RoadState_<ContainerAllocator> Type;

  RoadState_()
    : state(0)  {
    }
  RoadState_(const ContainerAllocator& _alloc)
    : state(0)  {
  (void)_alloc;
    }



   typedef uint16_t _state_type;
  _state_type state;


    enum { Init = 0u };
     enum { Block = 1u };
     enum { Evade = 2u };
     enum { Follow = 3u };
     enum { Pass = 4u };
     enum { Uturn = 5u };
     enum { WaitCross = 6u };
     enum { WaitLane = 7u };
     enum { WaitPass = 8u };
     enum { WaitStop = 9u };
     enum { Zone = 10u };
     enum { N_states = 11u };
 

  typedef boost::shared_ptr< ::art_msgs::RoadState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::art_msgs::RoadState_<ContainerAllocator> const> ConstPtr;

}; // struct RoadState_

typedef ::art_msgs::RoadState_<std::allocator<void> > RoadState;

typedef boost::shared_ptr< ::art_msgs::RoadState > RoadStatePtr;
typedef boost::shared_ptr< ::art_msgs::RoadState const> RoadStateConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::art_msgs::RoadState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::art_msgs::RoadState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace art_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'art_msgs': ['/home/amogh/rosws2/src/art_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::art_msgs::RoadState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::art_msgs::RoadState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::art_msgs::RoadState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::art_msgs::RoadState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::art_msgs::RoadState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::art_msgs::RoadState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::art_msgs::RoadState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e033b3ead3b77d2e264d454d67d06e4d";
  }

  static const char* value(const ::art_msgs::RoadState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe033b3ead3b77d2eULL;
  static const uint64_t static_value2 = 0x264d454d67d06e4dULL;
};

template<class ContainerAllocator>
struct DataType< ::art_msgs::RoadState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "art_msgs/RoadState";
  }

  static const char* value(const ::art_msgs::RoadState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::art_msgs::RoadState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Navigator Road state values\n\
# $Id$\n\
\n\
uint16 Init      = 0\n\
uint16 Block     = 1\n\
uint16 Evade     = 2\n\
uint16 Follow    = 3\n\
uint16 Pass      = 4\n\
uint16 Uturn     = 5\n\
uint16 WaitCross = 6\n\
uint16 WaitLane  = 7\n\
uint16 WaitPass  = 8\n\
uint16 WaitStop  = 9\n\
uint16 Zone      = 10\n\
uint16 N_states  = 11\n\
\n\
uint16 state\n\
";
  }

  static const char* value(const ::art_msgs::RoadState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::art_msgs::RoadState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoadState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::art_msgs::RoadState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::art_msgs::RoadState_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ART_MSGS_MESSAGE_ROADSTATE_H
