//#line 2 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the art_common package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __art_common__CAMERATRANSFORMCONFIG_H__
#define __art_common__CAMERATRANSFORMCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace art_common
{
  class CameraTransformConfigStatics;
  
  class CameraTransformConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(CameraTransformConfig &config, const CameraTransformConfig &max, const CameraTransformConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const CameraTransformConfig &config1, const CameraTransformConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, CameraTransformConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const CameraTransformConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, CameraTransformConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const CameraTransformConfig &config) const = 0;
      virtual void getValue(const CameraTransformConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level, 
          std::string a_description, std::string a_edit_method, T CameraTransformConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (CameraTransformConfig::* field);

      virtual void clamp(CameraTransformConfig &config, const CameraTransformConfig &max, const CameraTransformConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const CameraTransformConfig &config1, const CameraTransformConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, CameraTransformConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const CameraTransformConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, CameraTransformConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const CameraTransformConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const CameraTransformConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, CameraTransformConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, CameraTransformConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<CameraTransformConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(CameraTransformConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("left_front_camera_px"==(*_i)->name){left_front_camera_px = boost::any_cast<double>(val);}
        if("left_front_camera_py"==(*_i)->name){left_front_camera_py = boost::any_cast<double>(val);}
        if("left_front_camera_pz"==(*_i)->name){left_front_camera_pz = boost::any_cast<double>(val);}
        if("left_front_camera_roll"==(*_i)->name){left_front_camera_roll = boost::any_cast<double>(val);}
        if("left_front_camera_pitch"==(*_i)->name){left_front_camera_pitch = boost::any_cast<double>(val);}
        if("left_front_camera_yaw"==(*_i)->name){left_front_camera_yaw = boost::any_cast<double>(val);}
        if("center_front_camera_px"==(*_i)->name){center_front_camera_px = boost::any_cast<double>(val);}
        if("center_front_camera_py"==(*_i)->name){center_front_camera_py = boost::any_cast<double>(val);}
        if("center_front_camera_pz"==(*_i)->name){center_front_camera_pz = boost::any_cast<double>(val);}
        if("center_front_camera_roll"==(*_i)->name){center_front_camera_roll = boost::any_cast<double>(val);}
        if("center_front_camera_pitch"==(*_i)->name){center_front_camera_pitch = boost::any_cast<double>(val);}
        if("center_front_camera_yaw"==(*_i)->name){center_front_camera_yaw = boost::any_cast<double>(val);}
        if("right_front_camera_px"==(*_i)->name){right_front_camera_px = boost::any_cast<double>(val);}
        if("right_front_camera_py"==(*_i)->name){right_front_camera_py = boost::any_cast<double>(val);}
        if("right_front_camera_pz"==(*_i)->name){right_front_camera_pz = boost::any_cast<double>(val);}
        if("right_front_camera_roll"==(*_i)->name){right_front_camera_roll = boost::any_cast<double>(val);}
        if("right_front_camera_pitch"==(*_i)->name){right_front_camera_pitch = boost::any_cast<double>(val);}
        if("right_front_camera_yaw"==(*_i)->name){right_front_camera_yaw = boost::any_cast<double>(val);}
        if("velodyne_px"==(*_i)->name){velodyne_px = boost::any_cast<double>(val);}
        if("velodyne_py"==(*_i)->name){velodyne_py = boost::any_cast<double>(val);}
        if("velodyne_pz"==(*_i)->name){velodyne_pz = boost::any_cast<double>(val);}
        if("velodyne_roll"==(*_i)->name){velodyne_roll = boost::any_cast<double>(val);}
        if("velodyne_pitch"==(*_i)->name){velodyne_pitch = boost::any_cast<double>(val);}
        if("velodyne_yaw"==(*_i)->name){velodyne_yaw = boost::any_cast<double>(val);}
      }
    }

    double left_front_camera_px;
double left_front_camera_py;
double left_front_camera_pz;
double left_front_camera_roll;
double left_front_camera_pitch;
double left_front_camera_yaw;
double center_front_camera_px;
double center_front_camera_py;
double center_front_camera_pz;
double center_front_camera_roll;
double center_front_camera_pitch;
double center_front_camera_yaw;
double right_front_camera_px;
double right_front_camera_py;
double right_front_camera_pz;
double right_front_camera_roll;
double right_front_camera_pitch;
double right_front_camera_yaw;
double velodyne_px;
double velodyne_py;
double velodyne_pz;
double velodyne_roll;
double velodyne_pitch;
double velodyne_yaw;

    bool state;
    std::string name;

    
}groups;



//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_front_camera_px;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_front_camera_py;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_front_camera_pz;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_front_camera_roll;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_front_camera_pitch;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double left_front_camera_yaw;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double center_front_camera_px;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double center_front_camera_py;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double center_front_camera_pz;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double center_front_camera_roll;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double center_front_camera_pitch;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double center_front_camera_yaw;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_front_camera_px;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_front_camera_py;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_front_camera_pz;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_front_camera_roll;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_front_camera_pitch;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double right_front_camera_yaw;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double velodyne_px;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double velodyne_py;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double velodyne_pz;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double velodyne_roll;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double velodyne_pitch;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double velodyne_yaw;
//#line 218 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("CameraTransformConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const CameraTransformConfig &__max__ = __getMax__();
      const CameraTransformConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const CameraTransformConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const CameraTransformConfig &__getDefault__();
    static const CameraTransformConfig &__getMax__();
    static const CameraTransformConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const CameraTransformConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void CameraTransformConfig::ParamDescription<std::string>::clamp(CameraTransformConfig &config, const CameraTransformConfig &max, const CameraTransformConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class CameraTransformConfigStatics
  {
    friend class CameraTransformConfig;
    
    CameraTransformConfigStatics()
    {
CameraTransformConfig::GroupDescription<CameraTransformConfig::DEFAULT, CameraTransformConfig> Default("Default", "", 0, 0, true, &CameraTransformConfig::groups);
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_front_camera_px = -3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_front_camera_px = 3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_front_camera_px = 0.471;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("left_front_camera_px", "double", 0, "left front camera position x", "", &CameraTransformConfig::left_front_camera_px)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("left_front_camera_px", "double", 0, "left front camera position x", "", &CameraTransformConfig::left_front_camera_px)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_front_camera_py = -3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_front_camera_py = 3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_front_camera_py = 0.412;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("left_front_camera_py", "double", 0, "left front camera position y", "", &CameraTransformConfig::left_front_camera_py)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("left_front_camera_py", "double", 0, "left front camera position y", "", &CameraTransformConfig::left_front_camera_py)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_front_camera_pz = -3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_front_camera_pz = 3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_front_camera_pz = 2.184;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("left_front_camera_pz", "double", 0, "left front camera position z", "", &CameraTransformConfig::left_front_camera_pz)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("left_front_camera_pz", "double", 0, "left front camera position z", "", &CameraTransformConfig::left_front_camera_pz)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_front_camera_roll = -3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_front_camera_roll = 3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_front_camera_roll = 0.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("left_front_camera_roll", "double", 0, "left front camera roll", "", &CameraTransformConfig::left_front_camera_roll)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("left_front_camera_roll", "double", 0, "left front camera roll", "", &CameraTransformConfig::left_front_camera_roll)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_front_camera_pitch = -3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_front_camera_pitch = 3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_front_camera_pitch = -0.017;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("left_front_camera_pitch", "double", 0, "left front camera pitch", "", &CameraTransformConfig::left_front_camera_pitch)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("left_front_camera_pitch", "double", 0, "left front camera pitch", "", &CameraTransformConfig::left_front_camera_pitch)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_front_camera_yaw = -3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_front_camera_yaw = 3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_front_camera_yaw = 0.97;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("left_front_camera_yaw", "double", 0, "left front camera yaw", "", &CameraTransformConfig::left_front_camera_yaw)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("left_front_camera_yaw", "double", 0, "left front camera yaw", "", &CameraTransformConfig::left_front_camera_yaw)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.center_front_camera_px = -3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.center_front_camera_px = 3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.center_front_camera_px = 0.548;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("center_front_camera_px", "double", 0, "center front camera position x", "", &CameraTransformConfig::center_front_camera_px)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("center_front_camera_px", "double", 0, "center front camera position x", "", &CameraTransformConfig::center_front_camera_px)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.center_front_camera_py = -3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.center_front_camera_py = 3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.center_front_camera_py = 0.278;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("center_front_camera_py", "double", 0, "center front camera position y", "", &CameraTransformConfig::center_front_camera_py)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("center_front_camera_py", "double", 0, "center front camera position y", "", &CameraTransformConfig::center_front_camera_py)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.center_front_camera_pz = -3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.center_front_camera_pz = 3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.center_front_camera_pz = 2.184;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("center_front_camera_pz", "double", 0, "center front camera position z", "", &CameraTransformConfig::center_front_camera_pz)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("center_front_camera_pz", "double", 0, "center front camera position z", "", &CameraTransformConfig::center_front_camera_pz)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.center_front_camera_roll = -3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.center_front_camera_roll = 3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.center_front_camera_roll = 0.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("center_front_camera_roll", "double", 0, "center front camera roll", "", &CameraTransformConfig::center_front_camera_roll)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("center_front_camera_roll", "double", 0, "center front camera roll", "", &CameraTransformConfig::center_front_camera_roll)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.center_front_camera_pitch = -3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.center_front_camera_pitch = 3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.center_front_camera_pitch = 0.025;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("center_front_camera_pitch", "double", 0, "center front camera pitch", "", &CameraTransformConfig::center_front_camera_pitch)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("center_front_camera_pitch", "double", 0, "center front camera pitch", "", &CameraTransformConfig::center_front_camera_pitch)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.center_front_camera_yaw = -3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.center_front_camera_yaw = 3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.center_front_camera_yaw = -0.052;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("center_front_camera_yaw", "double", 0, "center front camera yaw", "", &CameraTransformConfig::center_front_camera_yaw)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("center_front_camera_yaw", "double", 0, "center front camera yaw", "", &CameraTransformConfig::center_front_camera_yaw)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_front_camera_px = -3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_front_camera_px = 3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_front_camera_px = 0.471;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("right_front_camera_px", "double", 0, "right front camera position x", "", &CameraTransformConfig::right_front_camera_px)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("right_front_camera_px", "double", 0, "right front camera position x", "", &CameraTransformConfig::right_front_camera_px)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_front_camera_py = -3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_front_camera_py = 3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_front_camera_py = 0.144;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("right_front_camera_py", "double", 0, "right front camera position y", "", &CameraTransformConfig::right_front_camera_py)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("right_front_camera_py", "double", 0, "right front camera position y", "", &CameraTransformConfig::right_front_camera_py)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_front_camera_pz = -3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_front_camera_pz = 3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_front_camera_pz = 2.184;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("right_front_camera_pz", "double", 0, "right front camera position z", "", &CameraTransformConfig::right_front_camera_pz)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("right_front_camera_pz", "double", 0, "right front camera position z", "", &CameraTransformConfig::right_front_camera_pz)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_front_camera_roll = -3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_front_camera_roll = 3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_front_camera_roll = 0.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("right_front_camera_roll", "double", 0, "right front camera roll", "", &CameraTransformConfig::right_front_camera_roll)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("right_front_camera_roll", "double", 0, "right front camera roll", "", &CameraTransformConfig::right_front_camera_roll)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_front_camera_pitch = -3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_front_camera_pitch = 3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_front_camera_pitch = 0.022;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("right_front_camera_pitch", "double", 0, "right front camera pitch", "", &CameraTransformConfig::right_front_camera_pitch)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("right_front_camera_pitch", "double", 0, "right front camera pitch", "", &CameraTransformConfig::right_front_camera_pitch)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_front_camera_yaw = -3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_front_camera_yaw = 3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_front_camera_yaw = -1.035;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("right_front_camera_yaw", "double", 0, "right front camera yaw", "", &CameraTransformConfig::right_front_camera_yaw)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("right_front_camera_yaw", "double", 0, "right front camera yaw", "", &CameraTransformConfig::right_front_camera_yaw)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.velodyne_px = -3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.velodyne_px = 3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.velodyne_px = 0.393;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("velodyne_px", "double", 0, "velodyne position x", "", &CameraTransformConfig::velodyne_px)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("velodyne_px", "double", 0, "velodyne position x", "", &CameraTransformConfig::velodyne_px)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.velodyne_py = -3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.velodyne_py = 3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.velodyne_py = 0.278;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("velodyne_py", "double", 0, "velodyne position y", "", &CameraTransformConfig::velodyne_py)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("velodyne_py", "double", 0, "velodyne position y", "", &CameraTransformConfig::velodyne_py)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.velodyne_pz = -3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.velodyne_pz = 3.0;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.velodyne_pz = 2.4;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("velodyne_pz", "double", 0, "velodyne position z", "", &CameraTransformConfig::velodyne_pz)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("velodyne_pz", "double", 0, "velodyne position z", "", &CameraTransformConfig::velodyne_pz)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.velodyne_roll = -3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.velodyne_roll = 3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.velodyne_roll = 0.0062133721371;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("velodyne_roll", "double", 0, "velodyne roll", "", &CameraTransformConfig::velodyne_roll)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("velodyne_roll", "double", 0, "velodyne roll", "", &CameraTransformConfig::velodyne_roll)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.velodyne_pitch = -3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.velodyne_pitch = 3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.velodyne_pitch = 0.0163537350912;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("velodyne_pitch", "double", 0, "velodyne pitch", "", &CameraTransformConfig::velodyne_pitch)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("velodyne_pitch", "double", 0, "velodyne pitch", "", &CameraTransformConfig::velodyne_pitch)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.velodyne_yaw = -3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.velodyne_yaw = 3.14159265359;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.velodyne_yaw = -0.02155;
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("velodyne_yaw", "double", 0, "velodyne yaw", "", &CameraTransformConfig::velodyne_yaw)));
//#line 293 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraTransformConfig::AbstractParamDescriptionConstPtr(new CameraTransformConfig::ParamDescription<double>("velodyne_yaw", "double", 0, "velodyne yaw", "", &CameraTransformConfig::velodyne_yaw)));
//#line 246 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(CameraTransformConfig::AbstractGroupDescriptionConstPtr(new CameraTransformConfig::GroupDescription<CameraTransformConfig::DEFAULT, CameraTransformConfig>(Default)));
//#line 356 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<CameraTransformConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<CameraTransformConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<CameraTransformConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    CameraTransformConfig __max__;
    CameraTransformConfig __min__;
    CameraTransformConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const CameraTransformConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static CameraTransformConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &CameraTransformConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const CameraTransformConfig &CameraTransformConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const CameraTransformConfig &CameraTransformConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const CameraTransformConfig &CameraTransformConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<CameraTransformConfig::AbstractParamDescriptionConstPtr> &CameraTransformConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<CameraTransformConfig::AbstractGroupDescriptionConstPtr> &CameraTransformConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const CameraTransformConfigStatics *CameraTransformConfig::__get_statics__()
  {
    const static CameraTransformConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = CameraTransformConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __CAMERATRANSFORMRECONFIGURATOR_H__
